<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ActivityLog;
use App\Models\User;

class AdminController extends Controller
{
    /**
     * Display admin dashboard with statistics and activity analytics.
     */
    public function dashboard()
    {
        /*
        |--------------------------------------------------------------------------
        | Dashboard Statistics
        |--------------------------------------------------------------------------
        */

        $stats = [
            'total_users' => User::count(),

            'total_admins' => User::where('is_admin', true)->count(),

            'total_activities' => ActivityLog::count(),

            'today_activities' => ActivityLog::whereDate(
                'created_at',
                today()
            )->count(),
        ];


        /*
        |--------------------------------------------------------------------------
        | Recent Activities
        |--------------------------------------------------------------------------
        */

        $recentActivities = ActivityLog::with('user')
            ->latest()
            ->take(10)
            ->get();


        /*
        |--------------------------------------------------------------------------
        | Activity Chart - Last 7 Days
        |--------------------------------------------------------------------------
        */

        $activityChart = ActivityLog::selectRaw(
            'DATE(created_at) as date, COUNT(*) as count'
        )
            ->where(
                'created_at',
                '>=',
                now()->subDays(7)
            )
            ->groupBy('date')
            ->orderBy('date')
            ->get();


        /*
        |--------------------------------------------------------------------------
        | NEW: Activity By Action
        |--------------------------------------------------------------------------
        |
        | Shows how many times each action was performed.
        |
        | Example:
        | create = 15
        | update = 20
        | delete = 5
        | login  = 10
        | logout = 8
        |
        */

        $activityByAction = ActivityLog::selectRaw(
            'action, COUNT(*) as count'
        )
            ->groupBy('action')
            ->orderByDesc('count')
            ->get();


        /*
        |--------------------------------------------------------------------------
        | NEW: Top Active Users
        |--------------------------------------------------------------------------
        |
        | Shows the top 5 users based on the number of
        | activity logs generated by them.
        |
        */

        $topActiveUsers = ActivityLog::selectRaw(
            'user_id, COUNT(*) as count'
        )
            ->whereNotNull('user_id')
            ->with('user')
            ->groupBy('user_id')
            ->orderByDesc('count')
            ->take(5)
            ->get();


        /*
        |--------------------------------------------------------------------------
        | Dashboard View
        |--------------------------------------------------------------------------
        */

        return view(
            'admin.dashboard',
            compact(
                'stats',
                'recentActivities',
                'activityChart',
                'activityByAction',
                'topActiveUsers'
            )
        );
    }
}